### ISSUE TITLE
Unnecessary re-rendering of NoteItems

### ISSUE THREAD

**Issue by pythonpioneer** [pythonpioneer/my-notes-frontend#104]
## Issue

**Issue Type:** `[Bug]`

**Issue Category:** `[Frontend]`

**`Issue Desc:`**
- The `NoteItem` component triggers a re-render.
- Whenever we add or update any note in the note array, every note will re-render.
- Probably, the `NoteBox` component is re-rendering.

**Comment by pythonpioneer** [comment]
When we create a note then in response we get the whole array and we are updating the entire array that's why the re-rendering is happening when taking notes.

**Comment by pythonpioneer** [comment]
The `EditNote` component is also rendering twice, and the reason behind this is the `openEditor` props value gets updated. The value turns from `false to true` and `true to false` and these two changes enforce the rendering of `EditNote` component and `NoteItem` component.

**Comment by pythonpioneer** [comment]
We can try the `reselect` library to prevent the re-render. let's try it out.

**Comment by pythonpioneer** [comment]
I tried to `memoise` the components to prevent unnecessary re-rendering, but the approach is not working. and the `reselect` memoised selector way is also not working.

**Comment by pythonpioneer** [comment]
Let's reproduce the issue in a different project and try to resolve it in a separate environment. This approach can help us to isolate the problem and potentially find a solution.

**Comment by dksingla** [comment]
React.Memo must have fixed the issue if the NoteItem component is stateless.

**Comment by pythonpioneer** [comment]
Thank you very much @dksingla. I removed the `noteType` and `themeStatus` states from the `NoteItem` and also removed the `isLoading` state manipulation from the redux-reducers and now, this is working fine.

**Comment by dksingla** [comment]
You can pass the values as props if required.

**Comment by pythonpioneer** [comment]
> You can pass the values as props if required.

Yes, I passed states as props in the `NoteItem` component. 
Selecting the `themeStatus` and `noteType` in the `NoteItem` component was not a good idea because I had already selected those states in the `Notebox` component and from there, we can simply pass those states as props.
Thank you so much!!.

**Comment by pythonpioneer** [comment]
> It seems like whenever the notes array gets updated the `Notebox` component re-rendered.

The `Notebox` component will re-render to render the `NoteItem`, but It must not render every `NoteItem`, and to resolve this issue (#104), we can remove the unnecessary states from the `NoteItem` component and we must memoise the `NoteItem` component.
