### ISSUE TITLE
Alerts

### ISSUE THREAD

**Issue by pythonpioneer** [pythonpioneer/my-notes-frontend#36]
### Issue

- Add alerts for all possible actions.
- For Logged In.
- For Logged out.
- For Notes Created.
- For Notes Deleted.
- For Notes Updated.
- For Invalid credentials
- For API response

> Inherit the issue after solving one or more requests, If any.

**Comment by Sky-De** [comment]
@pythonpioneer hi there, would you mind if i ask clarify these issue so we both can be at same page, for example what kind of alert? Js native alerts or custom alert?

**Comment by pythonpioneer** [comment]
@Sky-De It is a custom alert.

**Comment by Sky-De** [comment]
@pythonpioneer assign this to me, thanks

**Comment by pythonpioneer** [comment]
Someone already made a pull request(#39) regarding the issue(#36). Let me verify it, and then I will be able to assign it to you. I will inform you ASAP. Thank @Sky-De for your Interest.
