### ISSUE TITLE
Refactor Icons

### ISSUE THREAD

**Issue by pythonpioneer** [pythonpioneer/my-notes-frontend#40]
### Issue

- The app uses many icons.
- Create a dynamic component for the icon in the "src/icon" directory.
- Replace every icon in the app to the icon component
- `<i></i>` tag is used as icon. (To identify icons in the app)

**Comment by aniledev** [comment]
I can take this issue off your plate

**Comment by pythonpioneer** [comment]
Hi @aniledev, I assigned this to you.
